<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />
    <link rel="stylesheet" href="/css/main.css">

    <title>Boutique de mon association</title>
</head>

<body>
    <div class="container">
        <h1>Bienvenue sur notre boutique de Noël 🎄</h1>
        <p>
            Voici les différents produits que nous proposons à la livraison.
            Merci de faire votre sélection
        </p>

        <?php if (isset($data->error)) { ?>
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <?php echo $data->error ?>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        <?php } ?>

        <div class="pb-5">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 p-5 bg-white rounded shadow-sm mb-5">

                        <!-- Shopping cart table -->
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th scope="col" class="border-0 bg-light">
                                            <div class="p-2 px-3 text-uppercase">Produit</div>
                                        </th>
                                        <th scope="col" class="border-0 bg-light">
                                            <div class="py-2 text-uppercase">Tarif</div>
                                        </th>
                                        <th scope="col" class="border-0 bg-light">
                                            <div class="py-2 text-uppercase">Quantité</div>
                                        </th>
                                        <th scope="col" class="border-0 bg-light">
                                            <div class="py-2 text-uppercase">Supprimer</div>
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <th scope="row">
                                            <div class="p-2">
                                                <img src="/images/tree.jpg" alt="" width="70" class="img-fluid rounded shadow-sm">
                                                <div class="ml-3 d-inline-block align-middle">
                                                    <h5 class="mb-0"> <a href="#" class="text-dark d-inline-block align-middle">Sapin bio</a></h5>
                                                </div>
                                            </div>
                                        </th>
                                        <td class="align-middle"><strong>50,00 €</strong></td>
                                        <td class="align-middle">
                                            <select class="form-control" name="tree-count">
                                                <option>0</option>
                                                <option selected>1</option>
                                                <option>2</option>
                                                <option>3</option>
                                                <option>4</option>
                                                <option>5</option>
                                            </select>
                                        </td>
                                        <td class="align-middle text-center"><a href="javascript:;" class="text-danger" data-action="reset"><i class="fa fa-trash"></i></a></td>
                                    </tr>
                                    <tr>
                                        <th scope="row">
                                            <div class="p-2">
                                                <img src="/images/chocolate.jpg" alt="" width="70" class="img-fluid rounded shadow-sm">
                                                <div class="ml-3 d-inline-block align-middle">
                                                    <h5 class="mb-0"><a href="#" class="text-dark d-inline-block">Chocolat artisanal</a></h5>
                                                </div>
                                            </div>
                                        </th>
                                        <td class="align-middle"><strong>20,00 €</strong></td>
                                        <td class="align-middle">
                                            <select class="form-control" name="chocolate-count">
                                                <option>0</option>
                                                <option selected>1</option>
                                                <option>2</option>
                                                <option>3</option>
                                                <option>4</option>
                                                <option>5</option>
                                            </select>
                                        </td>
                                        <td class="align-middle text-center"><a href="javascript:;" class="text-danger" data-action="reset"><i class="fa fa-trash"></i></a></td>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th scope="row">
                                            <div class="p-2">
                                                <img src="/images/beer.jpg" alt="" width="70" class="img-fluid rounded shadow-sm">
                                                <div class="ml-3 d-inline-block align-middle">
                                                    <h5 class="mb-0"> <a href="#" class="text-dark d-inline-block">Bière artisanale</a></h5>
                                                </div>
                                            </div>
                                        <td class="align-middle"><strong>10,00 €</strong></td>
                                        <td class="align-middle">
                                            <select class="form-control" name="beer-count">
                                                <option>0</option>
                                                <option selected>1</option>
                                                <option>2</option>
                                                <option>3</option>
                                                <option>4</option>
                                                <option>5</option>
                                            </select>
                                        </td>
                                        <td class="align-middle text-center"><a href="javascript:;" class="text-danger" data-action="reset"><i class="fa fa-trash"></i></a></td>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <!-- End -->
                    </div>
                </div>

                <form method="POST">
                    <input name="address" type="hidden" value="<?php echo $data->address ?? '' ?>" />
                    <input name="zipcode" type="hidden" value="<?php echo $data->zipcode ?? '' ?>" />
                    <input name="city" type="hidden" value="<?php echo $data->city ?? '' ?>" />
                    <input name="country" type="hidden" value="<?php echo $data->country ?? 'FRA' ?>" />
                    <input name="amount" type="hidden" value=""  />

                    <div class="row py-5 p-4 bg-white rounded shadow-sm">
                        <div class="col-lg-6">
                            <div class="bg-light rounded-pill px-4 py-3 text-uppercase fw-bold">Coordonnées</div>
                            <div class="p-4">
                                <div class="mb-3">
                                    <label for="firstname" class="form-label">Prénom</label>
                                    <input type="text" class="form-control" id="firstname" name="firstname" value="<?php echo $data->firstname ?? '' ?>" required>
                                </div>
                                <div class="mb-3">
                                    <label for="lastname" class="form-label">Nom</label>
                                    <input type="text" class="form-control" id="lastname" name="lastname" value="<?php echo $data->lastname ?? '' ?>" required>
                                </div>
                                <div class="form-check form-switch">
                                    <input class="form-check-input" type="checkbox" id="iscompany" name="iscompany" <?php echo $data->isCompany ? 'checked' : '' ?>>
                                    <label class="form-check-label" for="iscompany">Paiement en tant que société ?</label>
                                </div>
                                <div id="companyContainer" class="mb-3" style="<?php echo $data->isCompany ? '' : 'display:none' ?>">
                                    <label for="company" class="form-label">Société</label>
                                    <input type="text" class="form-control" id="company" name="company" value="<?php echo $data->company ?? '' ?>">
                                </div>
                                <div class="mb-3">
                                    <label for="email" class="form-label">Email</label>
                                    <input type="email" class="form-control" id="email" name="email" value="<?php echo $data->email ?? '' ?>" required>
                                </div>
                                <div class="mb-3">
                                    <label for="birthdate" class="form-label">Date de naissance</label>
                                    <input type="date" class="form-control" id="birthdate" name="birthdate" value="<?php echo $data->birthdate ?? '' ?>" required>
                                </div>
                                <div class="mb-3">
                                    <label for="address" class="form-label">Addresse</label>
                                    <input type="text" class="form-control" id="address" name="address-auto" value="<?php echo ($data->address ?? '') . ' ' . ($data->zipcode ?? '') . ' ' . ($data->city ?? '') ?>" required>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="bg-light rounded-pill px-4 py-3 text-uppercase fw-bold">Résumé</div>
                            <div class="p-4">
                                <p class="font-italic mb-4">Des frais de port s'appliquent en fonction de votre commande.</p>
                                <ul class="list-unstyled mb-4">
                                    <li class="d-flex justify-content-between py-3 border-bottom"><strong class="text-muted">Sous total</strong><strong data-item="amount"></strong></li>
                                    <li class="d-flex justify-content-between py-3 border-bottom"><strong class="text-muted">Frais de port</strong><strong data-item="fee"></strong></li>
                                    <li class="d-flex justify-content-between py-3 border-bottom"><strong class="text-muted">Total</strong>
                                        <h5 class="fw-bold" data-item="total"></h5>
                                    </li>
                                </ul>
                                <button type="submit" class="btn btn-dark rounded-pill py-2 btn-block">Passer au paiement</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <!-- Optional JavaScript; choose one of the two! -->

        <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>

        <script src="/js/form.js"></script>
        <script src="/js/address.js"></script>
</body>

</html>