<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" />
        <link rel="stylesheet" href="/css/main.css">

        <title>Boutique de mon association</title>
    </head>
    <body>
        <div class="container">
            <?php if($_GET['code'] == "succeeded") { ?>
                <h1>Super 🎉</h1>
                <p>
                    Votre paiement s'est bien déroulé.<br/>
                    Nous vous tiendrons rapidement au courant de l'avancement de votre commande.
                </p>
            <?php } else if($_GET['code'] == "refused") { ?>
                <h1>Mince 🤦</h1>
                <p>
                    Votre paiement a été refusé.<br/>
                    Vous pouvez réessayer en <a href="/">remplissant de nouveau le formulaire</a>.
                </p>
            <?php } else { ?>
                <h1>Mince 🤦</h1>
                <p>
                    Il y a eu un problème lors de votre paiement.<br/>
                    <?php 
                        if($_GET['error']) {
                            echo "Pour la raison : " . $_GET['error'] . '<br/>';
                        } 
                    ?>
                    Vous pouvez réessayer en <a href="/">remplissant de nouveau le formulaire</a>.
                </p>
            <?php } ?>
        </div>
    </body>
</html>